spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    driverClassName: org.postgresql.Driver
    password: password
    platform: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG